.TH ENGINEER 1 "01 01 2016 FIXME" "engineer 0.0.1"

.SH NAME
engineer \- a demo application

.SH SYNOPSIS
.B engineer
[-L] [-C] [-V] [-h]

.SH DESCRIPTION

Engineer is a demo application to show how to integrate EFL and autotools into a
cross platform build. You should be able to generate an executable easily for all
target supported by EFL with this engineer.

With no option, the program starts and display an Hello World.


.SH OPTIONS

.TP
.B -L, --license
Show license.

.TP
.B -C, --copyright
Show copyright.

.TP
.B -V, --version
Show program version.

.TP
.B -h, --help
Print list of options with short description.


.SH BUGS

Reports are welcome. Send them at enlightenment-devel@lists.sourceforge.net.


.SH HOMEPAGE

http://enlightenment.org


.SH AUTHORS

Matthew Kolar <mjkolar@charter.net> and various contributors.
